# Generated by Django 3.1 on 2021-03-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0002_report_edit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='edit_user',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
